config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    # Only use applications_controller to manage OAuth2 applications
    skip_controllers :tokens, :token_info, :authorized_applications
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  resource :users, only: :create, path: '/signup'
  
  get '/signup', to: 'users#new'

  resource :sessions, only: %i[create destroy]
  
  get '/login', to: 'sessions#new'

  resources :keywords, only: %i[index show create]

  namespace :api do
    namespace :v1 do
      use_doorkeeper do
        # Only need the tokens_controller for API V1
        controllers tokens: 'tokens'
        
        skip_controllers :applications, :authorizations, :token_info, :authorized_applications
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resource :users, only: :create
      resources :keywords, only: %i[index show create]
    end
  end
end

app/views/shared/_flash_messages.html.slim
- if notice.present?
    .alert.alert-success = notice

- if alert.present?
    .alert.alert-danger = alert

app/views/shared/_nav.html.slim
nav class="navbar py-4 px-5 bg-dark"
  == link_to t('app.title'), root_path, class: "text-white"

  .menu
    - if authenticated?
      span.text-white
        == t('app.greeting_html', username: current_user.username)

      li class="nav-item dropdown d-inline-block align-middle"
        a class="nav-link dropdown-toggle text-white" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
        .dropdown-menu.dropdown-menu-right
          == link_to t('keyword.keywords'), keywords_path, class: "dropdown-item"
          == link_to t('auth.logout'), sessions_path, method: :delete, class: "dropdown-item"
          
    - else
      == link_to t('auth.login'), login_path, class: "text-white mr-4"
      == link_to t('auth.signup'), signup_path, class: "btn btn-outline-light align-baseline"